### ISSUE TITLE
Generalisation to any fandom wiki

### ISSUE THREAD

**Issue by nk-fouque** [AlexandreCarlton/twewy-graphql#1]
Hi, does this have a lot of things specific to the TWEWY wiki or is this easy to modify to be used with any fandom wiki ?

**Comment by AlexandreCarlton** [comment]
Hi,

This was an afternoon of tinkering with the XML dump available and is very specific to TWEWY (and not even half-finished).

Apologies for the false advertisement :sweat_smile:
